manifest:
  version: "1.2"

  remotes:
    - name: ingchips
      url-base: https://github.com/ingchips

  projects:
    - name: zephyr
      remote: ingchips
      repo-path: zephyr
      revision: dev_ingchips_west_test
      path: zephyr
      import:
        name-allowlist:
          - cmsis

    - name: hal_ingchips
      remote: ingchips
      repo-path: ING918XX_SDK_SOURCE
      revision: v9.1.1
      path: modules/hal/ingchips
      clone-depth: 1

  self:
    path: manifest
